---
# This playbook contains common plays that will be run on all nodes.

- name: Install Common Tools
  apt: name={{ item }} state=present
  with_items:
   - telnet
   - jq
   - htop
   - zip 
   - unzip
   - python-pip
  become: yes
  tags:
    - tools